#  GitHub Actions 工作流程的名稱
name: Java 演算法程式碼自動化建構與執行 - 無套件主類別

on:
  push:
    branches: [ "main" ] # 當程式碼被推送到 'main' 分支時，觸發執行
  pull_request:
    branches: [ "main" ] # 當有 Pull Request (PR) 到 'main' 分支時，觸發執行

jobs:
  build_and_run:
    runs-on: ubuntu-latest # 這個工作會在一個基於 Ubuntu 的虛擬機器上執行

    steps:
    - uses: actions/checkout@v4
      name: 下載Repository程式碼

    - name: 設定 Java 開發環境 (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17' # 請根據您的 Eclipse 專案實際使用的 Java 版本修改
        distribution: 'temurin'

    - name: 編譯 Java 程式碼
      run: |
        mkdir -p bin
        # 如果您的 .java 檔案都在 'src' 資料夾，請將下一行改為：find src -name "*.java" -print | xargs javac -d bin
        find . -name "*.java" -print | xargs javac -d bin

    - name: 執行您的 Java 演算法程式碼 # 重要：這裡假設您的主類別沒有 package 宣告
      # 請根據您實際的主類別名稱，從 Main, Solution, Algorithm 中選擇一個，或替換成您自己的名稱
      # 例如，如果您的主類別檔案是 `MyAlgorithm.java`，內容是 `public class MyAlgorithm { ... main ... }`，
      # 那麼這裡就寫 `MyAlgorithm`
      run: java -cp bin Main # <-- 這裡已修改為 'Main'，請依實際情況替換為您的主類別名稱
